//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Product_Number { get; set; }
        public string Description { get; set; }
        public int Units_On_Hand { get; set; }
        public decimal Price { get; set; }
    }
}
